### ISSUE TITLE
Implement Linux backend

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/gfx.mod#6]
The initial commit of bgfxgraphics only supports Win32.
We will need to implement support for Linux.

**Comment by GWRon** [comment]
Bump ;-)

**Comment by GWRon** [comment]
Thought about playing with it...but it is still win-only :-)

Are there plans to somewhen use bgfx or is it more or less on hold with so many other things left to do?

**Comment by woollybah** [comment]
I've decided to sit it on top of SDL, so this is no longer required.

**Comment by GWRon** [comment]
Do you mean using SDL as backend _for_ bgfx... Or to use the SDL graphics backend _instead_ of bgfx?

**Comment by woollybah** [comment]
bgfx creates frame buffer/graphics contexts.. You need to provide a window for it to render onto.
SDL is a window provider.

There's certainly little sense me writing Window management code for multiple platforms when we already have something that does it already.

**Comment by GWRon** [comment]
Yes but SDL offers more than just a new window (like glfw) which is why I asked.


So you plan to use SDL to create the window...and bgfx than gets this window passed to create the graphics context.

This windows creation was what was missing in bgfx.mod for linux/mac.


Did not see your commits (forgot to click "watch").

**Comment by GWRon** [comment]
Just tried the newest commit (with the newest bcc - because of the "enum fix") and can confirm that it works on my intel hd driven Windows 10 notebook.
